


import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;




/**
 *
 * @author pace_
 */
public class ItemAgregar extends javax.swing.JPanel {
    private ClienteGUI c;
    
  
    /**
     * Creates new form itemAmigo
     */
    public ItemAgregar(String nombre,ClienteGUI cliente) {
        initComponents();
        this.labelNombreUsuario.setText(nombre);
        this.c = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreUsuario = new javax.swing.JLabel();
        botonAgregarr = new javax.swing.JButton();

        labelNombreUsuario.setText("Nombre Usuairio");

        botonAgregarr.setText("Agregar");
        botonAgregarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botonAgregarr)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreUsuario)
                    .addComponent(botonAgregarr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarrActionPerformed

        this.setVisible(false);
       c.getUser().addAmigo(this.labelNombreUsuario.getText());
       int a = c.actualizarListaAmigos();
       c.actualizarListaNoAmigos();
        
         
          
        
            
       
    }//GEN-LAST:event_botonAgregarrActionPerformed

    public JButton getBotonMensajear() {
        return botonAgregarr;
    }

    public void setBotonMensajear(JButton botonMensajear) {
        this.botonAgregarr = botonMensajear;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarr;
    private javax.swing.JLabel labelNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
