
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;




/**
 *
 * @author pace_
 */
public class ItemAmigo extends javax.swing.JPanel {
    private ClienteGUI c;
    Conversacion conv;
  
    /**
     * Creates new form itemAmigo
     */
    public ItemAmigo(String nombre,ClienteGUI cliente) {
        initComponents();
        this.labelNombreAmigo.setText(nombre);
        this.c = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreAmigo = new javax.swing.JLabel();
        botonMensajear = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        labelNombreAmigo.setText("Nombre Amigo");

        botonMensajear.setText("Mensajear");
        botonMensajear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMensajearActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreAmigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMensajear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreAmigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(botonMensajear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonMensajearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMensajearActionPerformed

        // Genera un nuemo cuadro de conversacion
         conv = new Conversacion(this.labelNombreAmigo.getText(),this.c);
        conv.setBounds(conv.getBounds());
        conv.setVisible(true);
        try {
            c.getSalida().println(c.encriptar("ms"));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(ItemAmigo.class.getName()).log(Level.SEVERE, null, ex);
        }
      int cont=0;
       c.setVisible(false);
        
         
          
        
            
       
    }//GEN-LAST:event_botonMensajearActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
            this.setVisible(false);
       c.getUser().removeAmigo(this.labelNombreAmigo.getText());
       int a = c.actualizarListaAmigos();
       c.actualizarListaNoAmigos();

        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarButtonActionPerformed

    public JButton getBotonMensajear() {
        return botonMensajear;
    }

    public void setBotonMensajear(JButton botonMensajear) {
        this.botonMensajear = botonMensajear;
    }

    public JButton getEliminarButton() {
        return eliminarButton;
    }

    public void setEliminarButton(JButton eliminarButton) {
        this.eliminarButton = eliminarButton;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMensajear;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel labelNombreAmigo;
    // End of variables declaration//GEN-END:variables
}
