

/**
 *
 * @author Ignacio Diaz Romero
 */
public class ItemMensaje extends javax.swing.JPanel {
    /**
     * Creates new form ItemMensaje
     */
    public ItemMensaje(String mensaje) {
        initComponents();
        Mensaje.setText(mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mensaje = new javax.swing.JLabel();

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        Mensaje.setText("Mensaje");
        add(Mensaje);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    // End of variables declaration//GEN-END:variables
}
